#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2008 Sun Microsystems, Inc. All rights reserved.
# Use is subject to license terms.
#
# Portions Copyight 2009 Matt Ingenthron.  All rights reserved.
#
# ident	"@(#)memcached	1.2	08/03/29 SMI"

. /lib/svc/share/smf_include.sh

# SMF_FMRI is the name of the target service. This allows multiple instances
# to use the same script.


getproparg() {
val=`svcprop -p "$1" memcached`
[ -n "$val" ] && echo "$val"
}

MCBIN="/opt/northscale/bin"
MCOPTIONS="`getproparg memcached/options`"
MEMBASE=`prtconf | grep Mem | cut -f 3 -d " "`
MEMUSE=`expr $MEMBASE - 1024`
MCOPTIONS="$MCOPTIONS -m $MEMUSE"

case "$1" in
'start')
"${MCBIN}/memcached" $MCOPTIONS &
;;

'stop')
smf_kill_contract $2 TERM 1
;;

*)
echo "Usage: $0 {start|stop}"
exit 1
;;

esac
#exit $SMF_EXIT_OK
